// Generated by Wrangler on Sat May 11 2024 17:52:26 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
  DB: D1Database;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  GOOGLE_CALLBACK_URL: string;
  SESSION_SECRET: string;
  SESSION_KV: D1KvNamespace;
}
