// Code generated by sqlc-gen-ts-d1. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
//   sqlc-gen-ts-d1 v0.0.0-a@a3d312f03e80d6530ea7be50c1b39cf2e34cfa846d91751973ed078cb2cddecc

export type Users = {
  id: string;
  createdAt: string | null;
  updatedAt: string | null;
  email: string;
  username: string;
};

